// <auto-generated />
using System;
using Data.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250403172701_TextType")]
    partial class TextType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Answer", b =>
                {
                    b.Property<int>("answerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("answerId"), 1L, 1);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("answerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("questionId")
                        .HasColumnType("int");

                    b.Property<int>("value")
                        .HasColumnType("int");

                    b.HasKey("answerId");

                    b.HasIndex("questionId");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("Domain.Bukayo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("bukayos");
                });

            modelBuilder.Entity("Domain.Cart", b =>
                {
                    b.Property<int>("cartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cartId"), 1L, 1);

                    b.Property<int?>("PatientuserId")
                        .HasColumnType("int");

                    b.Property<int?>("SpecialistuserId")
                        .HasColumnType("int");

                    b.Property<int>("communityId")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("state")
                        .HasColumnType("int");

                    b.Property<int>("transmitterId")
                        .HasColumnType("int");

                    b.Property<string>("transmitterInitial")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("userType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cartId");

                    b.HasIndex("PatientuserId");

                    b.HasIndex("SpecialistuserId");

                    b.ToTable("carts");
                });

            modelBuilder.Entity("Domain.CartAnswer", b =>
                {
                    b.Property<int>("cartAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cartAnswerId"), 1L, 1);

                    b.Property<int>("cartId")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("read")
                        .HasColumnType("bit");

                    b.Property<int>("receiverId")
                        .HasColumnType("int");

                    b.Property<string>("receiverInitial")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("stickerId")
                        .HasColumnType("int");

                    b.HasKey("cartAnswerId");

                    b.HasIndex("cartId");

                    b.ToTable("cartAnswers");
                });

            modelBuilder.Entity("Domain.CompleteQuestionnaires", b =>
                {
                    b.Property<int>("completeQuestionnaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("completeQuestionnaireId"), 1L, 1);

                    b.Property<DateTime>("dateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<int>("patientId")
                        .HasColumnType("int");

                    b.Property<int>("questionnaireId")
                        .HasColumnType("int");

                    b.Property<int?>("testId")
                        .HasColumnType("int");

                    b.HasKey("completeQuestionnaireId");

                    b.HasIndex("testId");

                    b.ToTable("completeQuestionnaires");
                });

            modelBuilder.Entity("Domain.Date", b =>
                {
                    b.Property<int>("dateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dateId"), 1L, 1);

                    b.Property<int?>("SpecialistuserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("done")
                        .HasColumnType("bit");

                    b.Property<string>("hour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("patientConfirm")
                        .HasColumnType("bit");

                    b.Property<int?>("patientuserId")
                        .HasColumnType("int");

                    b.Property<string>("place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("sentBySpecialist")
                        .HasColumnType("bit");

                    b.Property<bool>("specialistConfirm")
                        .HasColumnType("bit");

                    b.Property<string>("specialistNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("dateId");

                    b.HasIndex("SpecialistuserId");

                    b.HasIndex("patientuserId");

                    b.ToTable("dates");
                });

            modelBuilder.Entity("Domain.DateRequest", b =>
                {
                    b.Property<int>("dateRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dateRequestId"), 1L, 1);

                    b.Property<int?>("CitadateId")
                        .HasColumnType("int");

                    b.Property<int?>("SpecialistuserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("dateCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("dateRequestId");

                    b.HasIndex("CitadateId");

                    b.HasIndex("SpecialistuserId");

                    b.ToTable("dateRequests");
                });

            modelBuilder.Entity("Domain.Diary", b =>
                {
                    b.Property<int>("diaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("diaryId"), 1L, 1);

                    b.HasKey("diaryId");

                    b.ToTable("diaries");
                });

            modelBuilder.Entity("Domain.Emotion", b =>
                {
                    b.Property<int>("emotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("emotionId"), 1L, 1);

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("emotionId");

                    b.ToTable("emotions");
                });

            modelBuilder.Entity("Domain.Flower", b =>
                {
                    b.Property<int>("flowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("flowerId"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("flowerId");

                    b.ToTable("flowers");
                });

            modelBuilder.Entity("Domain.Goal", b =>
                {
                    b.Property<int>("goalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("goalId"), 1L, 1);

                    b.Property<int?>("PatientuserId")
                        .HasColumnType("int");

                    b.Property<string>("desription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("flowerId")
                        .HasColumnType("int");

                    b.Property<string>("logoUlr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("stickerId")
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("goalId");

                    b.HasIndex("PatientuserId");

                    b.ToTable("goals");
                });

            modelBuilder.Entity("Domain.ImageModel", b =>
                {
                    b.Property<int>("imageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("imageId"), 1L, 1);

                    b.Property<int?>("flowerId")
                        .HasColumnType("int");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("imageId");

                    b.HasIndex("flowerId");

                    b.ToTable("ImageModel");
                });

            modelBuilder.Entity("Domain.InAppText", b =>
                {
                    b.Property<int>("textId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("textId"), 1L, 1);

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("textType")
                        .HasColumnType("int");

                    b.HasKey("textId");

                    b.ToTable("inAppTexts");
                });

            modelBuilder.Entity("Domain.Note", b =>
                {
                    b.Property<int>("noteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("noteId"), 1L, 1);

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("diaryId")
                        .HasColumnType("int");

                    b.Property<int>("emotionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("visible")
                        .HasColumnType("bit");

                    b.HasKey("noteId");

                    b.HasIndex("diaryId");

                    b.HasIndex("emotionId");

                    b.ToTable("notes");
                });

            modelBuilder.Entity("Domain.NotificationModel", b =>
                {
                    b.Property<int>("notificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("notificationId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PatientuserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PostponeUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("emitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("notificationType")
                        .HasColumnType("int");

                    b.Property<int?>("recomendationId")
                        .HasColumnType("int");

                    b.Property<int?>("recomendationType")
                        .HasColumnType("int");

                    b.Property<string>("reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("stickerId")
                        .HasColumnType("int");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("notificationId");

                    b.HasIndex("PatientuserId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("Domain.Opps", b =>
                {
                    b.Property<int>("BuserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuserId"), 1L, 1);

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<DateTime>("bornDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("bukayoSakaDiaryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("relationalToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuserId");

                    b.HasIndex("bukayoSakaDiaryId");

                    b.ToTable("opps");
                });

            modelBuilder.Entity("Domain.Patient", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"), 1L, 1);

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<DateTime>("bornDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("diaryId")
                        .HasColumnType("int");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("progressId")
                        .HasColumnType("int");

                    b.Property<string>("registerState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("relationalToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("settingsId")
                        .HasColumnType("int");

                    b.Property<string>("sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("specialistuserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("syncDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("termsAndConditionsId")
                        .HasColumnType("int");

                    b.Property<int>("testId")
                        .HasColumnType("int");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userInterfaceId")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.HasIndex("diaryId");

                    b.HasIndex("progressId");

                    b.HasIndex("settingsId");

                    b.HasIndex("specialistuserId");

                    b.HasIndex("termsAndConditionsId");

                    b.HasIndex("testId");

                    b.HasIndex("userInterfaceId");

                    b.ToTable("patients");
                });

            modelBuilder.Entity("Domain.PatientRequest", b =>
                {
                    b.Property<int>("patientRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("patientRequestId"), 1L, 1);

                    b.Property<int?>("SpecialistuserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("patientuserId")
                        .HasColumnType("int");

                    b.HasKey("patientRequestId");

                    b.HasIndex("SpecialistuserId");

                    b.HasIndex("patientuserId");

                    b.ToTable("PatientRequest");
                });

            modelBuilder.Entity("Domain.Progress", b =>
                {
                    b.Property<int>("progressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("progressId"), 1L, 1);

                    b.Property<DateTime?>("begginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("lastDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("stage")
                        .HasColumnType("int");

                    b.HasKey("progressId");

                    b.ToTable("progresses");
                });

            modelBuilder.Entity("Domain.Question", b =>
                {
                    b.Property<int>("questionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("questionId"), 1L, 1);

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("questionnaireId")
                        .HasColumnType("int");

                    b.Property<string>("statement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("questionId");

                    b.HasIndex("questionnaireId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("Domain.Questionnaire", b =>
                {
                    b.Property<int>("questionnaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("questionnaireId"), 1L, 1);

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("objective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("questionnaireName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("questionnaireId");

                    b.ToTable("questionnaires");
                });

            modelBuilder.Entity("Domain.QuestionnaireForUser", b =>
                {
                    b.Property<int>("questionnaireForUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("questionnaireForUserId"), 1L, 1);

                    b.Property<int>("questionnaireId")
                        .HasColumnType("int");

                    b.Property<int?>("testId")
                        .HasColumnType("int");

                    b.HasKey("questionnaireForUserId");

                    b.HasIndex("testId");

                    b.ToTable("questionnairesForUsers");
                });

            modelBuilder.Entity("Domain.QuestionnaireResult", b =>
                {
                    b.Property<int>("questionnaireResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("questionnaireResultId"), 1L, 1);

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("questionnaireId")
                        .HasColumnType("int");

                    b.Property<string>("result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("value")
                        .HasColumnType("int");

                    b.HasKey("questionnaireResultId");

                    b.HasIndex("questionnaireId");

                    b.ToTable("QuestionnaireResult");
                });

            modelBuilder.Entity("Domain.QuestionnairesHistory", b =>
                {
                    b.Property<int>("questionnairesHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("questionnairesHistoryId"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("questionnaireId")
                        .HasColumnType("int");

                    b.Property<int?>("testId")
                        .HasColumnType("int");

                    b.HasKey("questionnairesHistoryId");

                    b.HasIndex("testId");

                    b.ToTable("questionnairesHistories");
                });

            modelBuilder.Entity("Domain.Recomendation", b =>
                {
                    b.Property<int>("recomendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("recomendationId"), 1L, 1);

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("subTitle")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("recomendationId");

                    b.ToTable("Recomendation");
                });

            modelBuilder.Entity("Domain.RecomendationComplete", b =>
                {
                    b.Property<int>("recomendationCompleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("recomendationCompleteId"), 1L, 1);

                    b.Property<int?>("PatientuserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<int>("recomendationId")
                        .HasColumnType("int");

                    b.HasKey("recomendationCompleteId");

                    b.HasIndex("PatientuserId");

                    b.ToTable("recomendationComplete");
                });

            modelBuilder.Entity("Domain.SakaNotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BukayoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BukayoId");

                    b.ToTable("sakaNotes");
                });

            modelBuilder.Entity("Domain.SettingsP", b =>
                {
                    b.Property<int>("settingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("settingsId"), 1L, 1);

                    b.Property<bool>("diaryActive")
                        .HasColumnType("bit");

                    b.Property<bool>("notificationsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("questionnaireActive")
                        .HasColumnType("bit");

                    b.HasKey("settingsId");

                    b.ToTable("settings");
                });

            modelBuilder.Entity("Domain.Specialist", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"), 1L, 1);

                    b.Property<string>("adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<DateTime>("bornDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("focus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("institution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("license")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("presentation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("relationalToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("termsAndConditionsId")
                        .HasColumnType("int");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.HasIndex("termsAndConditionsId");

                    b.ToTable("specialists");
                });

            modelBuilder.Entity("Domain.Stage", b =>
                {
                    b.Property<int>("stageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stageId"), 1L, 1);

                    b.HasKey("stageId");

                    b.ToTable("stages");
                });

            modelBuilder.Entity("Domain.StageRequest", b =>
                {
                    b.Property<int>("stageRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stageRequestId"), 1L, 1);

                    b.Property<int?>("dayRange")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stageId")
                        .HasColumnType("int");

                    b.Property<int?>("value")
                        .HasColumnType("int");

                    b.HasKey("stageRequestId");

                    b.HasIndex("stageId");

                    b.ToTable("StageRequest");
                });

            modelBuilder.Entity("Domain.Sticker", b =>
                {
                    b.Property<int>("stickerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stickerId"), 1L, 1);

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("stickerId");

                    b.ToTable("stickers");
                });

            modelBuilder.Entity("Domain.TermsAndConditions", b =>
                {
                    b.Property<int>("termsAndConditionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("termsAndConditionsId"), 1L, 1);

                    b.Property<string>("termsAndConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("termsAndConditionsId");

                    b.ToTable("terms");
                });

            modelBuilder.Entity("Domain.Test", b =>
                {
                    b.Property<int>("testId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("testId"), 1L, 1);

                    b.HasKey("testId");

                    b.ToTable("tests");
                });

            modelBuilder.Entity("Domain.TestInfoModel", b =>
                {
                    b.Property<int>("testInfoModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("testInfoModelId"), 1L, 1);

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("questionnairesHistoryId")
                        .HasColumnType("int");

                    b.Property<string>("result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("visible")
                        .HasColumnType("bit");

                    b.HasKey("testInfoModelId");

                    b.HasIndex("questionnairesHistoryId");

                    b.ToTable("TestInfoModel");
                });

            modelBuilder.Entity("Domain.TestQuestionWithAnswer", b =>
                {
                    b.Property<int>("testQuestionWithAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("testQuestionWithAnswerId"), 1L, 1);

                    b.Property<string>("answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("testInfoModelId")
                        .HasColumnType("int");

                    b.HasKey("testQuestionWithAnswerId");

                    b.HasIndex("testInfoModelId");

                    b.ToTable("TestQuestionWithAnswer");
                });

            modelBuilder.Entity("Domain.UserFlower", b =>
                {
                    b.Property<int>("userFlowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userFlowerId"), 1L, 1);

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<int>("flowerId")
                        .HasColumnType("int");

                    b.Property<int?>("position")
                        .HasColumnType("int");

                    b.Property<int>("state")
                        .HasColumnType("int");

                    b.Property<int?>("userInterfaceId")
                        .HasColumnType("int");

                    b.HasKey("userFlowerId");

                    b.HasIndex("flowerId");

                    b.HasIndex("userInterfaceId");

                    b.ToTable("UserFlower");
                });

            modelBuilder.Entity("Domain.UserInterface", b =>
                {
                    b.Property<int>("userInterfaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userInterfaceId"), 1L, 1);

                    b.Property<int>("backgroundUrl")
                        .HasColumnType("int");

                    b.Property<int>("themeId")
                        .HasColumnType("int");

                    b.HasKey("userInterfaceId");

                    b.ToTable("userInterfaces");
                });

            modelBuilder.Entity("Domain.UserSticker", b =>
                {
                    b.Property<int>("userStickerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userStickerId"), 1L, 1);

                    b.Property<int?>("position")
                        .HasColumnType("int");

                    b.Property<int>("stickerId")
                        .HasColumnType("int");

                    b.Property<int?>("userInterfaceId")
                        .HasColumnType("int");

                    b.HasKey("userStickerId");

                    b.HasIndex("stickerId");

                    b.HasIndex("userInterfaceId");

                    b.ToTable("UserSticker");
                });

            modelBuilder.Entity("Domain.Answer", b =>
                {
                    b.HasOne("Domain.Question", null)
                        .WithMany("answers")
                        .HasForeignKey("questionId");
                });

            modelBuilder.Entity("Domain.Cart", b =>
                {
                    b.HasOne("Domain.Patient", null)
                        .WithMany("carts")
                        .HasForeignKey("PatientuserId");

                    b.HasOne("Domain.Specialist", null)
                        .WithMany("communityCarts")
                        .HasForeignKey("SpecialistuserId");
                });

            modelBuilder.Entity("Domain.CartAnswer", b =>
                {
                    b.HasOne("Domain.Cart", null)
                        .WithMany("cartAnswers")
                        .HasForeignKey("cartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.CompleteQuestionnaires", b =>
                {
                    b.HasOne("Domain.Test", null)
                        .WithMany("completeQuestionnaires")
                        .HasForeignKey("testId");
                });

            modelBuilder.Entity("Domain.Date", b =>
                {
                    b.HasOne("Domain.Specialist", null)
                        .WithMany("dates")
                        .HasForeignKey("SpecialistuserId");

                    b.HasOne("Domain.Patient", "patient")
                        .WithMany("dates")
                        .HasForeignKey("patientuserId");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("Domain.DateRequest", b =>
                {
                    b.HasOne("Domain.Date", "Cita")
                        .WithMany()
                        .HasForeignKey("CitadateId");

                    b.HasOne("Domain.Specialist", null)
                        .WithMany("dateRequests")
                        .HasForeignKey("SpecialistuserId");

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("Domain.Goal", b =>
                {
                    b.HasOne("Domain.Patient", null)
                        .WithMany("goals")
                        .HasForeignKey("PatientuserId");
                });

            modelBuilder.Entity("Domain.ImageModel", b =>
                {
                    b.HasOne("Domain.Flower", null)
                        .WithMany("images")
                        .HasForeignKey("flowerId");
                });

            modelBuilder.Entity("Domain.Note", b =>
                {
                    b.HasOne("Domain.Diary", null)
                        .WithMany("notes")
                        .HasForeignKey("diaryId");

                    b.HasOne("Domain.Emotion", "emotion")
                        .WithMany()
                        .HasForeignKey("emotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("emotion");
                });

            modelBuilder.Entity("Domain.NotificationModel", b =>
                {
                    b.HasOne("Domain.Patient", null)
                        .WithMany("notifications")
                        .HasForeignKey("PatientuserId");
                });

            modelBuilder.Entity("Domain.Opps", b =>
                {
                    b.HasOne("Domain.Bukayo", "bukayoSakaDiary")
                        .WithMany()
                        .HasForeignKey("bukayoSakaDiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bukayoSakaDiary");
                });

            modelBuilder.Entity("Domain.Patient", b =>
                {
                    b.HasOne("Domain.Diary", "diary")
                        .WithMany()
                        .HasForeignKey("diaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Progress", "progress")
                        .WithMany()
                        .HasForeignKey("progressId");

                    b.HasOne("Domain.SettingsP", "settings")
                        .WithMany()
                        .HasForeignKey("settingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Specialist", "specialist")
                        .WithMany("patients")
                        .HasForeignKey("specialistuserId");

                    b.HasOne("Domain.TermsAndConditions", "termsAndConditions")
                        .WithMany()
                        .HasForeignKey("termsAndConditionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Test", "test")
                        .WithMany()
                        .HasForeignKey("testId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.UserInterface", "userInterface")
                        .WithMany()
                        .HasForeignKey("userInterfaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("diary");

                    b.Navigation("progress");

                    b.Navigation("settings");

                    b.Navigation("specialist");

                    b.Navigation("termsAndConditions");

                    b.Navigation("test");

                    b.Navigation("userInterface");
                });

            modelBuilder.Entity("Domain.PatientRequest", b =>
                {
                    b.HasOne("Domain.Specialist", null)
                        .WithMany("patientsRequests")
                        .HasForeignKey("SpecialistuserId");

                    b.HasOne("Domain.Patient", "patient")
                        .WithMany()
                        .HasForeignKey("patientuserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("patient");
                });

            modelBuilder.Entity("Domain.Question", b =>
                {
                    b.HasOne("Domain.Questionnaire", null)
                        .WithMany("questions")
                        .HasForeignKey("questionnaireId");
                });

            modelBuilder.Entity("Domain.QuestionnaireForUser", b =>
                {
                    b.HasOne("Domain.Test", null)
                        .WithMany("questionnaires")
                        .HasForeignKey("testId");
                });

            modelBuilder.Entity("Domain.QuestionnaireResult", b =>
                {
                    b.HasOne("Domain.Questionnaire", null)
                        .WithMany("questionnaireResults")
                        .HasForeignKey("questionnaireId");
                });

            modelBuilder.Entity("Domain.QuestionnairesHistory", b =>
                {
                    b.HasOne("Domain.Test", null)
                        .WithMany("questionnairesHistory")
                        .HasForeignKey("testId");
                });

            modelBuilder.Entity("Domain.RecomendationComplete", b =>
                {
                    b.HasOne("Domain.Patient", null)
                        .WithMany("completeRecomendations")
                        .HasForeignKey("PatientuserId");
                });

            modelBuilder.Entity("Domain.SakaNotes", b =>
                {
                    b.HasOne("Domain.Bukayo", null)
                        .WithMany("SakaNotes")
                        .HasForeignKey("BukayoId");
                });

            modelBuilder.Entity("Domain.Specialist", b =>
                {
                    b.HasOne("Domain.TermsAndConditions", "termsAndConditions")
                        .WithMany()
                        .HasForeignKey("termsAndConditionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("termsAndConditions");
                });

            modelBuilder.Entity("Domain.StageRequest", b =>
                {
                    b.HasOne("Domain.Stage", null)
                        .WithMany("stageRequests")
                        .HasForeignKey("stageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.TestInfoModel", b =>
                {
                    b.HasOne("Domain.QuestionnairesHistory", null)
                        .WithMany("testInfoModels")
                        .HasForeignKey("questionnairesHistoryId");
                });

            modelBuilder.Entity("Domain.TestQuestionWithAnswer", b =>
                {
                    b.HasOne("Domain.TestInfoModel", null)
                        .WithMany("testQuestionWithAnswers")
                        .HasForeignKey("testInfoModelId");
                });

            modelBuilder.Entity("Domain.UserFlower", b =>
                {
                    b.HasOne("Domain.Flower", "flower")
                        .WithMany()
                        .HasForeignKey("flowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.UserInterface", null)
                        .WithMany("userFlowers")
                        .HasForeignKey("userInterfaceId");

                    b.Navigation("flower");
                });

            modelBuilder.Entity("Domain.UserSticker", b =>
                {
                    b.HasOne("Domain.Sticker", "sticker")
                        .WithMany()
                        .HasForeignKey("stickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.UserInterface", null)
                        .WithMany("userStickers")
                        .HasForeignKey("userInterfaceId");

                    b.Navigation("sticker");
                });

            modelBuilder.Entity("Domain.Bukayo", b =>
                {
                    b.Navigation("SakaNotes");
                });

            modelBuilder.Entity("Domain.Cart", b =>
                {
                    b.Navigation("cartAnswers");
                });

            modelBuilder.Entity("Domain.Diary", b =>
                {
                    b.Navigation("notes");
                });

            modelBuilder.Entity("Domain.Flower", b =>
                {
                    b.Navigation("images");
                });

            modelBuilder.Entity("Domain.Patient", b =>
                {
                    b.Navigation("carts");

                    b.Navigation("completeRecomendations");

                    b.Navigation("dates");

                    b.Navigation("goals");

                    b.Navigation("notifications");
                });

            modelBuilder.Entity("Domain.Question", b =>
                {
                    b.Navigation("answers");
                });

            modelBuilder.Entity("Domain.Questionnaire", b =>
                {
                    b.Navigation("questionnaireResults");

                    b.Navigation("questions");
                });

            modelBuilder.Entity("Domain.QuestionnairesHistory", b =>
                {
                    b.Navigation("testInfoModels");
                });

            modelBuilder.Entity("Domain.Specialist", b =>
                {
                    b.Navigation("communityCarts");

                    b.Navigation("dateRequests");

                    b.Navigation("dates");

                    b.Navigation("patients");

                    b.Navigation("patientsRequests");
                });

            modelBuilder.Entity("Domain.Stage", b =>
                {
                    b.Navigation("stageRequests");
                });

            modelBuilder.Entity("Domain.Test", b =>
                {
                    b.Navigation("completeQuestionnaires");

                    b.Navigation("questionnaires");

                    b.Navigation("questionnairesHistory");
                });

            modelBuilder.Entity("Domain.TestInfoModel", b =>
                {
                    b.Navigation("testQuestionWithAnswers");
                });

            modelBuilder.Entity("Domain.UserInterface", b =>
                {
                    b.Navigation("userFlowers");

                    b.Navigation("userStickers");
                });
#pragma warning restore 612, 618
        }
    }
}
