// <auto-generated />
using System;
using Data.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CuestionarioPaciente", b =>
                {
                    b.Property<int>("CuestionariosIdCuestionario")
                        .HasColumnType("int");

                    b.Property<int>("PacienteIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("CuestionariosIdCuestionario", "PacienteIdUsuario");

                    b.HasIndex("PacienteIdUsuario");

                    b.ToTable("CuestionarioPaciente");
                });

            modelBuilder.Entity("Domain.Carta", b =>
                {
                    b.Property<int>("IdCarta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarta"), 1L, 1);

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EspecialistaIdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmisor")
                        .HasColumnType("int");

                    b.Property<int?>("PacienteIdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("inicialEmisor")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("IdCarta");

                    b.HasIndex("EspecialistaIdUsuario");

                    b.HasIndex("PacienteIdUsuario");

                    b.ToTable("Cartas");
                });

            modelBuilder.Entity("Domain.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCita"), 1L, 1);

                    b.Property<bool>("ConfirmadaPorEspecialista")
                        .HasColumnType("bit");

                    b.Property<bool>("ConfirmadaPorPaciente")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EspecialistaIdUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lugar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PacienteIdUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("Realizada")
                        .HasColumnType("bit");

                    b.HasKey("IdCita");

                    b.HasIndex("EspecialistaIdUsuario");

                    b.HasIndex("PacienteIdUsuario");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("Domain.Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComentario"), 1L, 1);

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaComentario")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PublicacionIdPublicacion")
                        .HasColumnType("int");

                    b.HasKey("IdComentario");

                    b.HasIndex("PublicacionIdPublicacion");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("Domain.ConfiguracionP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("DirioActivado")
                        .HasColumnType("bit");

                    b.Property<bool>("NotificacionesActivas")
                        .HasColumnType("bit");

                    b.Property<bool>("ProgresoActivado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ConfuguracionesPaciente");
                });

            modelBuilder.Entity("Domain.Cuestionario", b =>
                {
                    b.Property<int>("IdCuestionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuestionario"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instrucciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCuestionario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCuestionario");

                    b.ToTable("Cuestionarios");
                });

            modelBuilder.Entity("Domain.CuestionarioCompletado", b =>
                {
                    b.Property<int>("IdCuestionarioCompletado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuestionarioCompletado"), 1L, 1);

                    b.Property<int>("CuestionarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCompletado")
                        .HasColumnType("datetime2");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("IdCuestionarioCompletado");

                    b.HasIndex("PacienteId");

                    b.ToTable("CuestionarioCompletados");
                });

            modelBuilder.Entity("Domain.Emocion", b =>
                {
                    b.Property<int>("IdEmocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmocion"), 1L, 1);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmocion");

                    b.ToTable("Emociones");
                });

            modelBuilder.Entity("Domain.Especialista", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<string>("CedulaProfesional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Enfoque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Presentacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TerminosycondicionesIdTerminosYCondiciones")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenRelacional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicaion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("TerminosycondicionesIdTerminosYCondiciones");

                    b.ToTable("Especialistas");
                });

            modelBuilder.Entity("Domain.Flor", b =>
                {
                    b.Property<int>("IdFlor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFlor"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFlor");

                    b.ToTable("Flores");
                });

            modelBuilder.Entity("Domain.FloresDelUsuarioModel", b =>
                {
                    b.Property<int>("StickerIdSticker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StickerIdSticker"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("Etapa")
                        .HasColumnType("int");

                    b.Property<int>("FlorIdFlor")
                        .HasColumnType("int");

                    b.Property<int?>("PacienteIdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.HasKey("StickerIdSticker");

                    b.HasIndex("FlorIdFlor");

                    b.HasIndex("PacienteIdUsuario");

                    b.ToTable("FloresDelUsuario");
                });

            modelBuilder.Entity("Domain.HistoryTestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdCuestionario")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PacienteIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteIdUsuario");

                    b.ToTable("HistorialesCuestionariosCompletados");
                });

            modelBuilder.Entity("Domain.ImageModel", b =>
                {
                    b.Property<int>("IdImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImage"), 1L, 1);

                    b.Property<int?>("FlorIdFlor")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdImage");

                    b.HasIndex("FlorIdFlor");

                    b.ToTable("ImageModel");
                });

            modelBuilder.Entity("Domain.Logro", b =>
                {
                    b.Property<int>("IdLogro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLogro"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("idFlor")
                        .HasColumnType("int");

                    b.Property<int?>("idSticker")
                        .HasColumnType("int");

                    b.HasKey("IdLogro");

                    b.ToTable("Logros");
                });

            modelBuilder.Entity("Domain.Nota", b =>
                {
                    b.Property<int>("IdNota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNota"), 1L, 1);

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmocionIdEmocion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PacienteIdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("IdNota");

                    b.HasIndex("EmocionIdEmocion");

                    b.HasIndex("PacienteIdUsuario");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("Domain.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PacienteIdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoNotificacion")
                        .HasColumnType("int");

                    b.Property<int?>("TipoRecomendacion")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("idRecomandacion")
                        .HasColumnType("int");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("PacienteIdUsuario");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Domain.Paciente", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<int>("ConfiguracionId")
                        .HasColumnType("int");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int?>("EspecialistaIdUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TerminosycondicionesIdTerminosYCondiciones")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenRelacional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("registerSet")
                        .HasColumnType("bit");

                    b.HasKey("IdUsuario");

                    b.HasIndex("ConfiguracionId");

                    b.HasIndex("EspecialistaIdUsuario");

                    b.HasIndex("TerminosycondicionesIdTerminosYCondiciones");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Domain.Pregunta", b =>
                {
                    b.Property<int>("IdPregunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPregunta"), 1L, 1);

                    b.Property<int?>("CuestionarioIdCuestionario")
                        .HasColumnType("int");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdPregunta");

                    b.HasIndex("CuestionarioIdCuestionario");

                    b.ToTable("Pregunta");
                });

            modelBuilder.Entity("Domain.Publicacion", b =>
                {
                    b.Property<int>("IdPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPublicacion"), 1L, 1);

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPublicacion");

                    b.ToTable("Publicaciones");
                });

            modelBuilder.Entity("Domain.Recomendacion", b =>
                {
                    b.Property<int>("IdRecomendacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecomendacion"), 1L, 1);

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubTitulo")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRecomendacion");

                    b.ToTable("Recomendaciones");
                });

            modelBuilder.Entity("Domain.RecomendacionCompletada", b =>
                {
                    b.Property<int>("IdRecomendacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecomendacion"), 1L, 1);

                    b.Property<DateTime>("FechaCompletada")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("RecomendacionIdRecomendacion")
                        .HasColumnType("int");

                    b.HasKey("IdRecomendacion");

                    b.HasIndex("RecomendacionIdRecomendacion");

                    b.ToTable("RecomendacionCompletada");
                });

            modelBuilder.Entity("Domain.Respuesta", b =>
                {
                    b.Property<int>("IdRespuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRespuesta"), 1L, 1);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PreguntaIdPregunta")
                        .HasColumnType("int");

                    b.Property<string>("TextoRespuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRespuesta");

                    b.HasIndex("PreguntaIdPregunta");

                    b.ToTable("Respuesta");
                });

            modelBuilder.Entity("Domain.RespuestaCarta", b =>
                {
                    b.Property<int>("IdCarta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarta"), 1L, 1);

                    b.Property<int?>("CartaIdCarta")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdReceptor")
                        .HasColumnType("int");

                    b.Property<int?>("IdSticker")
                        .HasColumnType("int");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("LetraReceptor")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("IdCarta");

                    b.HasIndex("CartaIdCarta");

                    b.ToTable("RespuestaCarta");
                });

            modelBuilder.Entity("Domain.SolicitudCita", b =>
                {
                    b.Property<int>("IdSolicitudCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitudCita"), 1L, 1);

                    b.Property<int?>("CitaIdCita")
                        .HasColumnType("int");

                    b.Property<int?>("EspecialistaIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdSolicitudCita");

                    b.HasIndex("CitaIdCita");

                    b.HasIndex("EspecialistaIdUsuario");

                    b.ToTable("SolicitudesCita");
                });

            modelBuilder.Entity("Domain.SolicitudPaciente", b =>
                {
                    b.Property<int>("IdSolicitudPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitudPaciente"), 1L, 1);

                    b.Property<int?>("EspecialistaIdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("PacienteIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdSolicitudPaciente");

                    b.HasIndex("EspecialistaIdUsuario");

                    b.HasIndex("PacienteIdUsuario");

                    b.ToTable("SolicitudesPaciente");
                });

            modelBuilder.Entity("Domain.Sticker", b =>
                {
                    b.Property<int>("IdSticker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSticker"), 1L, 1);

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSticker");

                    b.ToTable("Sticker");
                });

            modelBuilder.Entity("Domain.StickerDeUsuarioModel", b =>
                {
                    b.Property<int>("IdStickerDeUsuarioModel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStickerDeUsuarioModel"), 1L, 1);

                    b.Property<int?>("PacienteIdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("Posicion")
                        .HasColumnType("int");

                    b.Property<int>("StickerIdSticker")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdStickerDeUsuarioModel");

                    b.HasIndex("PacienteIdUsuario");

                    b.HasIndex("StickerIdSticker");

                    b.ToTable("StickersDeUsuario");
                });

            modelBuilder.Entity("Domain.TerminosYCondiciones", b =>
                {
                    b.Property<int>("IdTerminosYCondiciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTerminosYCondiciones"), 1L, 1);

                    b.Property<string>("terminosYCondiciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTerminosYCondiciones");

                    b.ToTable("TerminosYCondiciones");
                });

            modelBuilder.Entity("Domain.TestInfoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HistoryTestModelId")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HistoryTestModelId");

                    b.ToTable("TestInfoModel");
                });

            modelBuilder.Entity("Domain.TestQuestionWithAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TestInfoModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestInfoModelId");

                    b.ToTable("TestQuestionWithAnswer");
                });

            modelBuilder.Entity("LogroPaciente", b =>
                {
                    b.Property<int>("PacientesIdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("logrosIdLogro")
                        .HasColumnType("int");

                    b.HasKey("PacientesIdUsuario", "logrosIdLogro");

                    b.HasIndex("logrosIdLogro");

                    b.ToTable("LogroPaciente");
                });

            modelBuilder.Entity("CuestionarioPaciente", b =>
                {
                    b.HasOne("Domain.Cuestionario", null)
                        .WithMany()
                        .HasForeignKey("CuestionariosIdCuestionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Paciente", null)
                        .WithMany()
                        .HasForeignKey("PacienteIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Carta", b =>
                {
                    b.HasOne("Domain.Especialista", null)
                        .WithMany("CartasDeComunidad")
                        .HasForeignKey("EspecialistaIdUsuario");

                    b.HasOne("Domain.Paciente", null)
                        .WithMany("Cartas")
                        .HasForeignKey("PacienteIdUsuario");
                });

            modelBuilder.Entity("Domain.Cita", b =>
                {
                    b.HasOne("Domain.Especialista", null)
                        .WithMany("Citas")
                        .HasForeignKey("EspecialistaIdUsuario");

                    b.HasOne("Domain.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("PacienteIdUsuario");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Domain.Comentario", b =>
                {
                    b.HasOne("Domain.Publicacion", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("PublicacionIdPublicacion");
                });

            modelBuilder.Entity("Domain.CuestionarioCompletado", b =>
                {
                    b.HasOne("Domain.Paciente", null)
                        .WithMany("cuestionarioCompletados")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Especialista", b =>
                {
                    b.HasOne("Domain.TerminosYCondiciones", "Terminosycondiciones")
                        .WithMany()
                        .HasForeignKey("TerminosycondicionesIdTerminosYCondiciones")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terminosycondiciones");
                });

            modelBuilder.Entity("Domain.FloresDelUsuarioModel", b =>
                {
                    b.HasOne("Domain.Flor", "Flor")
                        .WithMany()
                        .HasForeignKey("FlorIdFlor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Paciente", null)
                        .WithMany("FloresDelUsuario")
                        .HasForeignKey("PacienteIdUsuario");

                    b.Navigation("Flor");
                });

            modelBuilder.Entity("Domain.HistoryTestModel", b =>
                {
                    b.HasOne("Domain.Paciente", null)
                        .WithMany("HistorialCuestionarios")
                        .HasForeignKey("PacienteIdUsuario");
                });

            modelBuilder.Entity("Domain.ImageModel", b =>
                {
                    b.HasOne("Domain.Flor", null)
                        .WithMany("Imagenes")
                        .HasForeignKey("FlorIdFlor");
                });

            modelBuilder.Entity("Domain.Nota", b =>
                {
                    b.HasOne("Domain.Emocion", "Emocion")
                        .WithMany("Notas")
                        .HasForeignKey("EmocionIdEmocion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Paciente", null)
                        .WithMany("Notas")
                        .HasForeignKey("PacienteIdUsuario");

                    b.Navigation("Emocion");
                });

            modelBuilder.Entity("Domain.Notificacion", b =>
                {
                    b.HasOne("Domain.Paciente", null)
                        .WithMany("Notificaciones")
                        .HasForeignKey("PacienteIdUsuario");
                });

            modelBuilder.Entity("Domain.Paciente", b =>
                {
                    b.HasOne("Domain.ConfiguracionP", "Configuracion")
                        .WithMany()
                        .HasForeignKey("ConfiguracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Especialista", "Especialista")
                        .WithMany("Pacientes")
                        .HasForeignKey("EspecialistaIdUsuario");

                    b.HasOne("Domain.TerminosYCondiciones", "Terminosycondiciones")
                        .WithMany()
                        .HasForeignKey("TerminosycondicionesIdTerminosYCondiciones")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuracion");

                    b.Navigation("Especialista");

                    b.Navigation("Terminosycondiciones");
                });

            modelBuilder.Entity("Domain.Pregunta", b =>
                {
                    b.HasOne("Domain.Cuestionario", null)
                        .WithMany("Preguntas")
                        .HasForeignKey("CuestionarioIdCuestionario");
                });

            modelBuilder.Entity("Domain.RecomendacionCompletada", b =>
                {
                    b.HasOne("Domain.Recomendacion", null)
                        .WithMany("recomendacionCompletadas")
                        .HasForeignKey("RecomendacionIdRecomendacion");
                });

            modelBuilder.Entity("Domain.Respuesta", b =>
                {
                    b.HasOne("Domain.Pregunta", null)
                        .WithMany("Respuestas")
                        .HasForeignKey("PreguntaIdPregunta");
                });

            modelBuilder.Entity("Domain.RespuestaCarta", b =>
                {
                    b.HasOne("Domain.Carta", null)
                        .WithMany("Respuestas")
                        .HasForeignKey("CartaIdCarta");
                });

            modelBuilder.Entity("Domain.SolicitudCita", b =>
                {
                    b.HasOne("Domain.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("CitaIdCita");

                    b.HasOne("Domain.Especialista", null)
                        .WithMany("SolicitudesCita")
                        .HasForeignKey("EspecialistaIdUsuario");

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("Domain.SolicitudPaciente", b =>
                {
                    b.HasOne("Domain.Especialista", null)
                        .WithMany("solicitudPacientes")
                        .HasForeignKey("EspecialistaIdUsuario");

                    b.HasOne("Domain.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Domain.StickerDeUsuarioModel", b =>
                {
                    b.HasOne("Domain.Paciente", null)
                        .WithMany("Stickersds")
                        .HasForeignKey("PacienteIdUsuario");

                    b.HasOne("Domain.Sticker", "Sticker")
                        .WithMany()
                        .HasForeignKey("StickerIdSticker")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sticker");
                });

            modelBuilder.Entity("Domain.TestInfoModel", b =>
                {
                    b.HasOne("Domain.HistoryTestModel", null)
                        .WithMany("testInfoModels")
                        .HasForeignKey("HistoryTestModelId");
                });

            modelBuilder.Entity("Domain.TestQuestionWithAnswer", b =>
                {
                    b.HasOne("Domain.TestInfoModel", null)
                        .WithMany("TestQuestionWithAnswers")
                        .HasForeignKey("TestInfoModelId");
                });

            modelBuilder.Entity("LogroPaciente", b =>
                {
                    b.HasOne("Domain.Paciente", null)
                        .WithMany()
                        .HasForeignKey("PacientesIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Logro", null)
                        .WithMany()
                        .HasForeignKey("logrosIdLogro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Carta", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("Domain.Cuestionario", b =>
                {
                    b.Navigation("Preguntas");
                });

            modelBuilder.Entity("Domain.Emocion", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("Domain.Especialista", b =>
                {
                    b.Navigation("CartasDeComunidad");

                    b.Navigation("Citas");

                    b.Navigation("Pacientes");

                    b.Navigation("SolicitudesCita");

                    b.Navigation("solicitudPacientes");
                });

            modelBuilder.Entity("Domain.Flor", b =>
                {
                    b.Navigation("Imagenes");
                });

            modelBuilder.Entity("Domain.HistoryTestModel", b =>
                {
                    b.Navigation("testInfoModels");
                });

            modelBuilder.Entity("Domain.Paciente", b =>
                {
                    b.Navigation("Cartas");

                    b.Navigation("Citas");

                    b.Navigation("FloresDelUsuario");

                    b.Navigation("HistorialCuestionarios");

                    b.Navigation("Notas");

                    b.Navigation("Notificaciones");

                    b.Navigation("Stickersds");

                    b.Navigation("cuestionarioCompletados");
                });

            modelBuilder.Entity("Domain.Pregunta", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("Domain.Publicacion", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("Domain.Recomendacion", b =>
                {
                    b.Navigation("recomendacionCompletadas");
                });

            modelBuilder.Entity("Domain.TestInfoModel", b =>
                {
                    b.Navigation("TestQuestionWithAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
